version: '3.3'

services:
  
  db:
    image: dockersamples/signup-db
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  web:
    image: dockersamples/signup-web
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

  save-handler:
    image: dockersamples/signup-save-handler
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

  index-handler:
    image: dockersamples/signup-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: sixeyed/kibana:nanoserver
    depends_on:
      - elasticsearch
    networks:
      - app-net

networks:
  app-net: